# Generated by Django 4.2.15 on 2024-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Roll_number', models.IntegerField(null=True)),
                ('Branch', models.CharField(max_length=20)),
                ('Year', models.CharField(max_length=15)),
                ('Semester', models.CharField(max_length=15)),
                ('Email_id', models.EmailField(max_length=254, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('DOB', models.DateField(null=True)),
                ('Score', models.IntegerField(null=True)),
            ],
        ),
    ]
