# Generated by Django 4.2.15 on 2024-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='Semester',
        ),
        migrations.AlterField(
            model_name='players',
            name='Roll_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
