# Generated by Django 4.2.15 on 2024-08-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_players_vr_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='vr_player',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vr_player',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
