# Generated by Django 4.2.15 on 2024-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vr_player_date_vr_player_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vr_player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\websocket\\ET\\ETweb\\static\\images\x07vatar'),
        ),
    ]
