# Generated by Django 4.2.15 on 2024-08-18 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vr_player_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vr_player',
            old_name='avatar',
            new_name='Avatar',
        ),
    ]
