# Generated by Django 4.2.15 on 2024-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_players_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\websocket\\ET\\ETweb\\media'),
        ),
    ]
