# Generated by Django 4.2.15 on 2024-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bgmi_players_th_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='vr_Players',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now=True)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Game', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Score', models.IntegerField(default=0)),
                ('play_time', models.DurationField(default=0)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='D:\\websocket\\ET\\ETweb\\media\\th')),
                ('Time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='vr_pirate_Players',
        ),
        migrations.DeleteModel(
            name='vr_pistol_Players',
        ),
        migrations.DeleteModel(
            name='vr_racer_Players',
        ),
        migrations.DeleteModel(
            name='vr_roller_Players',
        ),
        migrations.DeleteModel(
            name='vr_ultimechs_Players',
        ),
        migrations.DeleteModel(
            name='vr_zombie_Players',
        ),
        migrations.RenameField(
            model_name='bgmi_players',
            old_name='Phone',
            new_name='FP',
        ),
        migrations.RenameField(
            model_name='bgmi_players',
            old_name='Score',
            new_name='PP',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='Email_id',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='Roll_number',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='Year',
        ),
        migrations.AddField(
            model_name='bgmi_players',
            name='Rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bgmi_players',
            name='TP',
            field=models.IntegerField(null=True),
        ),
    ]
