# Generated by Django 4.2.15 on 2024-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_vr_players_delete_vr_pirate_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vr_players',
            name='Avatar',
            field=models.CharField(blank=True, null=True),
        ),
    ]
