# Generated by Django 4.2.15 on 2024-09-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_vr_players_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgmi_players',
            old_name='Name',
            new_name='Team_Name',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='FP',
        ),
        migrations.RemoveField(
            model_name='bgmi_players',
            name='Time',
        ),
        migrations.AddField(
            model_name='bgmi_players',
            name='KP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bgmi_players',
            name='game',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bgmi_players',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
